
api_decklist:
    pattern: /decklist/{decklist_id}.{_format}
    defaults:
        _controller: AppBundle:Api:decklist
        _format: json
    requirements:
        _format: json
        decklist_id: \d+

api_decklists:
    pattern: /decklists/by_date/{date}.{_format}
    defaults:
        _controller: AppBundle:Api:decklists
        _format: json
    requirements:
        _format: json
        date: \d\d\d\d-\d\d-\d\d

api_decks:
    pattern: /decks
    defaults:
        _controller: AppBundle:Api:decks

api_cards:
    pattern: /cards/
    defaults:
        _controller: AppBundle:Api:cards

api_card:
    pattern: /card/{card_code}.{_format}
    defaults:
        _controller: AppBundle:Api:card
        _format: json
    requirements:
        _format: json
        card_code: \d+

api_sets:
    pattern: /sets/
    defaults:
        _controller: AppBundle:Api:sets

api_set:
    pattern: /set/{pack_code}.{_format}
    defaults:
        _controller: AppBundle:Api:set
        _format: json
    requirements:
        _format: json|xml|xlsx|xls
        
user_info:
    pattern: /user_info
    defaults:
        _controller: AppBundle:User:info
        