
cards_list:
    pattern: /set/{pack_code}/{view}/{sort}/{page}
    defaults:
        _controller: AppBundle:Search:list
        view: list
        sort: set
        page: 1

cards_zoom:
    pattern: /card/{card_code}
    defaults:
        _controller: AppBundle:Search:zoom
    requirements:
        card_code: \d+

cards_cycle:
    pattern: /cycle/{cycle_code}/{view}/{sort}/{page}
    defaults:
        _controller: AppBundle:Search:cycle
        view: list
        sort: faction
        page: 1

cards_search:
    pattern: /search
    defaults:
        _controller: AppBundle:Search:form

cards_find:
    pattern: /find
    defaults:
        _controller: AppBundle:Search:find

cards_processSearchForm:
    pattern: /process
    defaults:
        _controller: AppBundle:Search:process
