admin_type:
    pattern:  /
    defaults: { _controller: "AppBundle:Type:index" }

admin_type_show:
    pattern:  /{id}/show
    defaults: { _controller: "AppBundle:Type:show" }

admin_type_new:
    pattern:  /new
    defaults: { _controller: "AppBundle:Type:new" }

admin_type_create:
    pattern:  /create
    defaults: { _controller: "AppBundle:Type:create" }
    requirements: { _method: post }

admin_type_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AppBundle:Type:edit" }

admin_type_update:
    pattern:  /{id}/update
    defaults: { _controller: "AppBundle:Type:update" }
    requirements: { _method: post|put }

admin_type_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AppBundle:Type:delete" }
    requirements: { _method: post|delete }
