AppBundle\Entity\Card:
    type: entity
    table: card
    manyToOne:
        pack:
            targetEntity: Pack
            inversedBy: cards
            joinColumn:
                name: pack_id
                referencedColumnName: id
        type:
            targetEntity: Type
            inversedBy: cards
            joinColumn:
                name: type_id
                referencedColumnName: id
        faction:
            targetEntity: Faction
            inversedBy: cards
            joinColumn:
                name: faction_id
                referencedColumnName: id
    oneToMany:
        reviews:
            targetEntity: Review
            orderBy: {'dateCreation':'DESC'}
            mappedBy: card
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 1024
            nullable: false
        class:
            type: string
            length: 1024
            nullable: true
        code:
            type: string
            length: 255
            nullable: false
        materials:
            type: smallint
            nullable: false
        research:
            type: smallint
            nullable: false
        energy:
            type: smallint
            nullable: false
        techLevel:
            type: smallint
            nullable: false
            column: tech_level
# operations and developments
        effect:
            type: string
            length: 255
            nullable: true
# start operations only
        operType:
            type: string
            length: 255
            nullable: true
            column: oper_type
        phase:
            type: string
            length: 255
            nullable: true
# end operations
# start ships only
        attack:
            type: smallint
            nullable: true
        size:
            type: string
            length: 255
            nullable: true
        hull:
            type: smallint
            nullable: true
        moduleOne:
            type: string
            length: 255
            nullable: true
            column: module_one
        modvalOne:
            type: smallint
            nullable: true
            column: modval_one
        moduleTwo:
            type: string
            length: 255
            nullable: true
            column: module_two
        modvalTwo:
            type: smallint
            nullable: true
            column: modval_two
        moduleThree:
            type: string
            length: 255
            nullable: true
            column: module_three
        modvalThree:
            type: smallint
            nullable: true
            column: modval_three
        engines:
            type: smallint
            nullable: true
        fuelCost:
            type: smallint
            nullable: true
            column: fuel_cost
# end ships
# start developments only
        structure:
            type: smallint
            nullable: true
        isHQ:
            type: boolean
            nullable: false
            column: is_hq
        isUnique:
            type: boolean
            nullable: false
            column: is_unique
# end developments
# start developments & sectors & core worlds
        stars:
            type: smallint
            nullable: true
        buildSlot:
            type: smallint
            nullable: true
            column: build_slot
        infantry:
            type: smallint
            nullable: true
        spaceAttack:
            type: smallint
            nullable: true
            column: space_attack
# end developments & sectors & core worlds
# start core worlds only
        minDeck:
            type: smallint
            nullable: true
            column: min_deck
        techSlots:
            type: smallint
            nullable: true
            column: tech_slots
        flexPoints:
            type: smallint
            nullable: true
            column: flex_points
# end core worlds
        flavor:
            type: text
            nullable: true
        artCredit:
            type: string
            length: 255
            nullable: true
            column: art_credit
        cardSet:
            type: string
            length: 255
            nullable: false
            column: card_set
        dateCreation:
            type: datetime
            nullable: false
            column: date_creation
            gedmo:
                timestampable:
                    on: create
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
            gedmo:
                timestampable:
                    on: update
        position:
            type: smallint
            nullable: false
        quantity:
            type: smallint
            nullable: false
